version: "3.9"

services:
  db:
    image: postgres:14.1
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=main
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  backend:
    restart: always
    build:
      context: ./backend
    command: sh -c "python src/manage.py collectstatic --noinput && python src/manage.py migrate && gunicorn --chdir ./src config.wsgi --bind 0.0.0.0:8000"
    volumes:
      - backend_uploads:/backend/src/uploads
      - backend_static:/backend/src/static
    environment:
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - IS_PRODUCTION=True
      - DB_NAME=main
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    volumes:
      - frontend_build:/frontend/dist

  app:
    image: nginx:1.21.6
    ports:
      - "80:8080"
    volumes:
      - ./app/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
      - frontend_build:/var/www/frontend
      - backend_static:/var/www/backend/static
    depends_on:
      - backend
      - frontend

volumes:
  frontend_build:
  db:
    driver: local
  backend_uploads:
    driver: local
  backend_static:
